# Generated by Django 5.0.6 on 2024-06-10 06:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'", regex='^\\+\\d{1,3}\\d{9,12}$')])),
                ('position', models.CharField(choices=[('senior-software-engineer', 'Senior Software Engineer'), ('project-manager', 'Project Manager'), ('it-consultant', 'IT Consultant'), ('data-analyst', 'Data Analyst'), ('network-engineer', 'Network Engineer')], max_length=30)),
                ('resume', models.FileField(upload_to='resumes/')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'", regex='^\\+\\d{1,3}\\d{9,12}$')])),
            ],
        ),
    ]
